
CREATE TABLE DOCUMENTS(
  DOC_ID INT PRIMARY KEY auto_increment,
  DOC_NAME VARCHAR(200),
  DOC_DESCRIPTION VARCHAR(500),
  IS_PUBLIC BOOLEAN,
  UPLOAD_DATE DATE
);

CREATE TABLE DOC_TO_BOP(
  DOC_ID INT,
  BOP_ID INT
);

CREATE TABLE BOP(
OP_ID INT PRIMARY KEY auto_increment,
OP_NAME VARCHAR(100),
OP_DESC VARCHAR(100),
OP_CREATE_TIME TIMESTAMP,
OP_CREAR INT
);



CREATE TABLE LOAN_TYPE(
ID INT PRIMARY KEY auto_increment,
OP_ID INT, 
LOAN_NAME VARCHAR(100),
PRODUCT_LOGO VARCHAR(1000),
LOAN_DESC VARCHAR(500)

);

CREATE TABLE LOAN_DOC(
	REQ_ID INT PRIMARY KEY,
    LOAN_TYPE INT,
	DOC_NAME VARCHAR(100),
	DOC_DESC VARCHAR(500)
    
);

CREATE TABLE OU_TYPE(
  ORG_TYPE_ID INT PRIMARY KEY auto_increment,
  ORGAN_NAME VARCHAR(200),
  ORG_TYPE_DESC VARCHAR(200)
);

CREATE TABLE OU(
  ORGAN_ID INT PRIMARY KEY auto_increment,
  ORGAN_TYPE INT,
  ORGAN_NAME VARCHAR(200),
  LAT_LANG VARCHAR(100)
);

CREATE TABLE BOP_OPERATOR(
  ID INT PRIMARY KEY auto_increment,
  FIRST_NAME VARCHAR(100),
  MIDLE_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  UNIT_ID INT,
  AUTHRIZED BOOLEAN,
  OU INT,
  AUTHORIZER INT,
  AUTH_TIME timestamp
);

CREATE TABLE POST_DOC_REQ(
	ID INT PRIMARY KEY auto_increment,
    DOC_NAME VARCHAR(200),
    PUPSE_DESC VARCHAR(500)
)
